spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url : jdbc:mysql://localhost:3306/blog_system_test
    username : root
    password : 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #上传配置
      enabled: true
      #单个文件最大大小
      max-file-size: 30MB
      #一次请求文件最大大小
      max-request-size: 100MB
file:
  upload:
    #文件保存路径
    path: C:\Users\miang\Desktop\img\
  coming:
    #文件访问路径
    path: http://localhost:80/
